import type { GitConfig, PRDetails, PRResult } from '../types/index';
import { logger } from '../utils/logger';
import { getRepoInfo } from '../utils/environment';

interface RepoIdentifier {
  owner: string;
  name: string;
}

export class PRCreator {
  private readonly config: GitConfig;

  constructor(config: GitConfig) {
    this.config = config;
  }

  /**
   * Create a pull/merge request on the configured provider.
   */
  public async createPR(details: PRDetails): Promise<PRResult> {
    const repo = this.resolveRepo();

    logger.info(`Creating PR on ${this.config.provider}: "${details.title}"`);

    switch (this.config.provider) {
      case 'github':
        return this.createGitHubPR(repo, details);
      case 'gitlab':
        return this.createGitLabMR(repo, details);
      case 'bitbucket':
        return this.createBitbucketPR(repo, details);
      default: {
        const provider: never = this.config.provider;
        throw new Error(`[MindHeal] Unsupported git provider: ${provider as string}`);
      }
    }
  }

  // ── Private helpers ──────────────────────────────────────────────────────────

  /**
   * Resolve the repository owner/name from config or by auto-detecting from
   * the git remote URL.
   */
  private resolveRepo(): RepoIdentifier {
    if (this.config.repoOwner && this.config.repoName) {
      return { owner: this.config.repoOwner, name: this.config.repoName };
    }

    const detected = getRepoInfo();
    if (detected) {
      logger.debug('Auto-detected repo info from git remote', detected);
      return detected;
    }

    throw new Error(
      '[MindHeal] Unable to determine repository owner/name. ' +
        'Set repoOwner and repoName in the git config, or ensure a valid git remote exists.',
    );
  }

  /**
   * Format the PR body with a healing summary markdown table.
   */
  private formatBody(rawBody: string): string {
    return [
      '## MindHeal - Automated Locator Fix',
      '',
      rawBody,
      '',
      '---',
      '*This PR was automatically generated by [MindHeal](https://github.com/nicholasgriffintn/mindheal).*',
    ].join('\n');
  }

  // ── GitHub ────────────────────────────────────────────────────────────────────

  private async createGitHubPR(repo: RepoIdentifier, details: PRDetails): Promise<PRResult> {
    const url = `https://api.github.com/repos/${repo.owner}/${repo.name}/pulls`;

    const body = {
      title: details.title,
      body: this.formatBody(details.body),
      head: details.sourceBranch,
      base: details.targetBranch,
    };

    const response = await this.request(url, body, {
      Authorization: `Bearer ${this.config.token}`,
      Accept: 'application/vnd.github.v3+json',
    });

    const data = (await response.json()) as { html_url: string; number: number };

    if (!response.ok) {
      const errorBody = JSON.stringify(data);
      throw new Error(`[MindHeal] GitHub PR creation failed (${response.status}): ${errorBody}`);
    }

    const prResult: PRResult = {
      url: data.html_url,
      number: data.number,
      provider: 'github',
    };

    // Best-effort: add labels and reviewers
    await this.addGitHubExtras(repo, prResult.number, details);

    logger.info(`GitHub PR created: ${prResult.url}`);
    return prResult;
  }

  /**
   * Add labels and request reviewers on a GitHub PR (non-critical).
   */
  private async addGitHubExtras(
    repo: RepoIdentifier,
    prNumber: number,
    details: PRDetails,
  ): Promise<void> {
    const base = `https://api.github.com/repos/${repo.owner}/${repo.name}`;
    const headers = {
      Authorization: `Bearer ${this.config.token}`,
      Accept: 'application/vnd.github.v3+json',
    };

    // Labels
    if (details.labels.length > 0) {
      try {
        await this.request(`${base}/issues/${prNumber}/labels`, { labels: details.labels }, headers);
      } catch (error) {
        logger.warn('[MindHeal] Failed to add labels to PR', error);
      }
    }

    // Reviewers
    if (details.reviewers.length > 0) {
      try {
        await this.request(
          `${base}/pulls/${prNumber}/requested_reviewers`,
          { reviewers: details.reviewers },
          headers,
        );
      } catch (error) {
        logger.warn('[MindHeal] Failed to request reviewers on PR', error);
      }
    }
  }

  // ── GitLab ────────────────────────────────────────────────────────────────────

  private async createGitLabMR(repo: RepoIdentifier, details: PRDetails): Promise<PRResult> {
    const encodedPath = encodeURIComponent(`${repo.owner}/${repo.name}`);
    const url = `https://gitlab.com/api/v4/projects/${encodedPath}/merge_requests`;

    const body = {
      title: details.title,
      description: this.formatBody(details.body),
      source_branch: details.sourceBranch,
      target_branch: details.targetBranch,
      labels: details.labels.join(','),
      reviewer_ids: [] as number[], // GitLab uses numeric IDs; usernames not directly supported
    };

    const response = await this.request(url, body, {
      'PRIVATE-TOKEN': this.config.token,
    });

    const data = (await response.json()) as { web_url: string; iid: number };

    if (!response.ok) {
      const errorBody = JSON.stringify(data);
      throw new Error(`[MindHeal] GitLab MR creation failed (${response.status}): ${errorBody}`);
    }

    const prResult: PRResult = {
      url: data.web_url,
      number: data.iid,
      provider: 'gitlab',
    };

    logger.info(`GitLab MR created: ${prResult.url}`);
    return prResult;
  }

  // ── Bitbucket ─────────────────────────────────────────────────────────────────

  private async createBitbucketPR(repo: RepoIdentifier, details: PRDetails): Promise<PRResult> {
    const url = `https://api.bitbucket.org/2.0/repositories/${repo.owner}/${repo.name}/pullrequests`;

    const body = {
      title: details.title,
      description: this.formatBody(details.body),
      source: { branch: { name: details.sourceBranch } },
      destination: { branch: { name: details.targetBranch } },
      reviewers: details.reviewers.map((username) => ({ username })),
      close_source_branch: true,
    };

    const response = await this.request(url, body, {
      Authorization: `Bearer ${this.config.token}`,
    });

    const data = (await response.json()) as {
      links: { html: { href: string } };
      id: number;
    };

    if (!response.ok) {
      const errorBody = JSON.stringify(data);
      throw new Error(
        `[MindHeal] Bitbucket PR creation failed (${response.status}): ${errorBody}`,
      );
    }

    const prResult: PRResult = {
      url: data.links.html.href,
      number: data.id,
      provider: 'bitbucket',
    };

    logger.info(`Bitbucket PR created: ${prResult.url}`);
    return prResult;
  }

  // ── HTTP helper ───────────────────────────────────────────────────────────────

  private async request(
    url: string,
    body: unknown,
    headers: Record<string, string>,
  ): Promise<Response> {
    try {
      return await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...headers,
        },
        body: JSON.stringify(body),
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`[MindHeal] HTTP request to ${url} failed: ${message}`);
    }
  }
}
