import type { MindHealConfig } from '../types/index';

export const DEFAULT_CONFIG: MindHealConfig = {
  ai: {
    provider: 'anthropic',
    apiKey: '',
    model: 'claude-sonnet-4-20250514',
    maxTokens: 1024,
    temperature: 0.1,
  },
  healing: {
    enabled: true,
    maxRetries: 3,
    strategies: ['cache', 'attribute', 'text', 'role', 'css', 'xpath', 'table', 'modal', 'enterprise', 'ai'],
    confidenceThreshold: 0.7,
    cacheHeals: true,
    cachePath: '.mindheal/cache.json',
    excludePatterns: [],
    domSnapshotDepth: 3,
    handleDialogs: true,
  },
  git: {
    enabled: true,
    provider: 'github',
    token: '',
    baseBranch: 'main',
    branchPrefix: 'mindheal/auto-fix',
    autoCreatePR: true,
    commitMessagePrefix: 'fix(locators):',
    prLabels: ['auto-heal', 'mindheal'],
    prReviewers: [],
  },
  reviewServer: {
    enabled: 'auto',
    port: 3000,
    openBrowser: true,
    autoCloseAfterReview: true,
  },
  reporting: {
    outputDir: '.mindheal/reports',
    generateHTML: true,
    generateJSON: true,
  },
  enterprise: {
    enabled: true,
    platform: 'auto',
    waitForLoad: true,
    loadTimeout: 15000,
    virtualScrolling: true,
    customStableAttributes: [],
    customDynamicIdPatterns: [],
  },
  analytics: {
    enabled: true,
    storePath: '.mindheal/analytics.json',
    trackLocators: true,
    trackStrategies: true,
    trackTestStability: true,
    maxEntries: 5000,
    retentionDays: 90,
  },
  smartRetry: {
    enabled: true,
    waitForNetworkIdle: true,
    networkIdleTimeout: 5000,
    exponentialBackoff: true,
    backoffBaseDelay: 500,
    backoffMaxDelay: 10000,
    flakyDetection: true,
    flakyThreshold: 3,
    flakyStorePath: '.mindheal/flaky-tests.json',
  },
  parallel: {
    enabled: true,
    lockTimeout: 10000,
    lockRetryInterval: 50,
    staleLockThreshold: 30000,
  },
  visualVerification: {
    enabled: false,
    screenshotDir: '.mindheal/screenshots',
    diffThreshold: 0.1,
    captureElement: true,
    captureFullPage: false,
    keepScreenshots: true,
  },
  rag: {
    enabled: true,
    storePath: '.mindheal/knowledge.json',
    maxContextChunks: 5,
    similarityThreshold: 0.3,
    sources: [
      'healing-history',
      'page-objects',
      'git-changes',
      'dom-snapshots',
      'component-docs',
      'test-specs',
    ],
    pageObjectPaths: ['pages', 'src/pages', 'page-objects'],
    componentDocPaths: [],
  },
  logging: {
    level: 'info',
  },
};
